// All cues use Tone.js synths so we don't need sample files.
// Volume scale: -∞ dB to 0 dB. Cues stay quiet vs music layer.

export const AUDIO_CUES = {
  colorSelect: {
    description: 'Soft wooden tap on color swatch click',
    type: 'synth',
    waveform: 'triangle',
    frequency: 880,
    duration: '32n',
    volume: 0.35,
    envelope: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.1 },
  },
  toolTogglePen: {
    description: 'Clean subtle tick for pen tool select',
    type: 'synth',
    waveform: 'sine',
    frequency: 1200,
    duration: '64n',
    volume: 0.25,
    envelope: { attack: 0.001, decay: 0.05, sustain: 0, release: 0.05 },
  },
  toolToggleCrayon: {
    description: 'Soft scuff for crayon tool select',
    type: 'noise',
    noiseType: 'brown',
    duration: '32n',
    volume: 0.2,
    envelope: { attack: 0.01, decay: 0.1, sustain: 0, release: 0.08 },
  },
  toolToggleText: {
    description: 'Soft mid tap for text tool select',
    type: 'synth',
    waveform: 'triangle',
    frequency: 660,
    duration: '32n',
    volume: 0.3,
    envelope: { attack: 0.001, decay: 0.07, sustain: 0, release: 0.08 },
  },
  toolToggleEraser: {
    description: 'Dry papery brush for eraser select',
    type: 'noise',
    noiseType: 'white',
    duration: '32n',
    volume: 0.18,
    envelope: { attack: 0.005, decay: 0.12, sustain: 0, release: 0.06 },
  },
  sizeAdjust: {
    description: 'Tiny tick at each slider increment',
    type: 'synth',
    waveform: 'sine',
    frequency: 1400,
    duration: '128n',
    volume: 0.18,
    envelope: { attack: 0.001, decay: 0.03, sustain: 0, release: 0.03 },
  },
  pinchStart: {
    description: 'The "plonk" — soft lift chime when pinch begins drawing',
    type: 'synth',
    waveform: 'sine',
    frequency: 523,
    duration: '16n',
    volume: 0.4,
    envelope: { attack: 0.01, decay: 0.15, sustain: 0.1, release: 0.3 },
  },
  pinchRelease: {
    description: 'Soft settle when pinch releases',
    type: 'synth',
    waveform: 'sine',
    frequency: 392,
    duration: '16n',
    volume: 0.28,
    envelope: { attack: 0.001, decay: 0.12, sustain: 0, release: 0.2 },
  },
  save: {
    description: 'Warm chord on save to Memory Book',
    type: 'polySynth',
    notes: ['C4', 'E4', 'G4'],
    duration: '4n',
    volume: 0.45,
    envelope: { attack: 0.05, decay: 0.3, sustain: 0.2, release: 0.8 },
  },
  clear: {
    description: 'Gentle descending sweep on canvas clear',
    type: 'sequence',
    waveform: 'sine',
    frequencies: [523, 392, 261],
    stepMs: 80,
    duration: '8n',
    volume: 0.32,
    envelope: { attack: 0.02, decay: 0.2, sustain: 0.05, release: 0.3 },
  },
  memoryBookOpen: {
    description: 'Soft page open chime',
    type: 'sequence',
    waveform: 'triangle',
    frequencies: [392, 523],
    stepMs: 90,
    duration: '8n',
    volume: 0.3,
    envelope: { attack: 0.02, decay: 0.15, sustain: 0.05, release: 0.25 },
  },
  keyPress: {
    description: 'Creamy typewriter tock per keypress',
    type: 'membrane',
    waveform: 'sine',
    frequency: 220,
    pitchDecay: 0.04,
    octaves: 2,
    duration: '32n',
    volume: 0.7,
    pitchVariance: 0.1,
    envelope: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.05 },
  },
  spaceBar: {
    description: 'Lower bassier tock for spacebar',
    type: 'membrane',
    waveform: 'sine',
    frequency: 140,
    pitchDecay: 0.05,
    octaves: 2,
    duration: '32n',
    volume: 0.65,
    pitchVariance: 0.06,
    envelope: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.06 },
  },
  enterKey: {
    description: 'Pronounced settle tock for enter',
    type: 'membrane',
    waveform: 'sine',
    frequency: 180,
    pitchDecay: 0.06,
    octaves: 2,
    duration: '16n',
    volume: 0.75,
    envelope: { attack: 0.001, decay: 0.14, sustain: 0, release: 0.1 },
  },
  backspace: {
    description: 'Soft descending tock for backspace',
    type: 'membrane',
    waveform: 'sine',
    frequency: 260,
    pitchDecay: 0.08,
    octaves: 3,
    duration: '32n',
    volume: 0.6,
    envelope: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.08 },
  },
};
