export const PALETTE = [
  {
    id: 'coral',
    hex: '#FA9189',
    name: 'Coral',
    instrument: 'Piano',
    toneType: 'Sampler',
    baseNote: 'C4',
    scaleNotes: ['C4', 'D4', 'E4', 'G4', 'A4'],
    audioFamily: 'daydream',
  },
  {
    id: 'peach',
    hex: '#FCAE7C',
    name: 'Peach',
    instrument: 'Acoustic Guitar',
    toneType: 'PluckSynth',
    baseNote: 'E3',
    scaleNotes: ['E3', 'G3', 'A3', 'B3', 'D4'],
    audioFamily: 'daydream',
  },
  {
    id: 'yellow',
    hex: '#FFE699',
    name: 'Yellow',
    instrument: 'Marimba',
    toneType: 'MetalSynth',
    baseNote: 'G4',
    scaleNotes: ['G4', 'A4', 'B4', 'D5', 'E5'],
    audioFamily: 'daydream',
  },
  {
    id: 'lemon',
    hex: '#F9FFB5',
    name: 'Lemon',
    instrument: 'Music Box',
    toneType: 'Synth',
    baseNote: 'B4',
    scaleNotes: ['B4', 'D5', 'E5', 'G5', 'A5'],
    audioFamily: 'daydream',
  },
  {
    id: 'mint',
    hex: '#B3F5BC',
    name: 'Mint',
    instrument: 'Harp',
    toneType: 'PluckSynth',
    baseNote: 'A3',
    scaleNotes: ['A3', 'C4', 'D4', 'E4', 'G4'],
    audioFamily: 'daydream',
  },
  {
    id: 'sky',
    hex: '#D6F6FF',
    name: 'Sky',
    instrument: 'Flute',
    toneType: 'FMSynth',
    baseNote: 'D5',
    scaleNotes: ['D5', 'E5', 'G5', 'A5', 'B5'],
    audioFamily: 'daydream',
  },
  {
    id: 'lavender',
    hex: '#E2CBF7',
    name: 'Lavender',
    instrument: 'Synth Pad',
    toneType: 'PolySynth',
    baseNote: 'F3',
    scaleNotes: ['F3', 'G3', 'A3', 'C4', 'D4'],
    audioFamily: 'daydream',
  },
  {
    id: 'lilac',
    hex: '#D1BDFF',
    name: 'Lilac',
    instrument: 'Cello',
    toneType: 'Sampler',
    baseNote: 'C3',
    scaleNotes: ['C3', 'D3', 'E3', 'G3', 'A3'],
    audioFamily: 'daydream',
  },
  // TWILIGHT (v2, included in constants but hidden in MVP UI)
  {
    id: 'eggplant',
    hex: '#483A5C',
    name: 'Eggplant',
    instrument: 'Upright Bass',
    toneType: 'Synth',
    baseNote: 'C2',
    scaleNotes: ['C2', 'D2', 'E2', 'G2', 'A2'],
    audioFamily: 'twilight',
  },
  {
    id: 'mauve',
    hex: '#B894B0',
    name: 'Mauve',
    instrument: 'Vinyl Synth Pad',
    toneType: 'AMSynth',
    baseNote: 'E3',
    scaleNotes: ['E3', 'G3', 'A3', 'B3', 'D4'],
    audioFamily: 'twilight',
  },
  {
    id: 'steel',
    hex: '#B3CDE0',
    name: 'Steel',
    instrument: 'Vibraphone',
    toneType: 'MetalSynth',
    baseNote: 'A4',
    scaleNotes: ['A4', 'C5', 'D5', 'E5', 'G5'],
    audioFamily: 'twilight',
  },
  {
    id: 'sage-cream',
    hex: '#DCDFD4',
    name: 'Sage Cream',
    instrument: 'Ambient Strings',
    toneType: 'PolySynth',
    baseNote: 'G3',
    scaleNotes: ['G3', 'A3', 'B3', 'D4', 'E4'],
    audioFamily: 'twilight',
  },
  {
    id: 'sage',
    hex: '#A1BD8F',
    name: 'Sage',
    instrument: 'Rhodes Piano',
    toneType: 'FMSynth',
    baseNote: 'D3',
    scaleNotes: ['D3', 'E3', 'G3', 'A3', 'B3'],
    audioFamily: 'twilight',
  },
];

export const MVP_PALETTE = PALETTE.filter((c) => c.audioFamily === 'daydream');

export function getColorById(id) {
  return PALETTE.find((c) => c.id === id);
}
